import { NextRequest, NextResponse } from "next/server";
import { revalidatePath } from "next/cache";
import { requireAdmin } from "@/lib/admin-auth";
import { prisma } from "@/lib/prisma";
import { slugify } from "@/lib/content-store";

type RouteProps={params:Promise<{id:string}>};
function lines(v:unknown){return String(v??"").split("\n").map(x=>x.trim()).filter(Boolean)}
function priceValue(v:unknown){const n=Number(v??0);return Number.isFinite(n)&&n>=0&&Math.round(n*1000)===n*1000?n:null}
async function categoryId(name:string){const n=name.trim()||"SaaS";const s=slugify(n)||"saas";return (await prisma.toolCategory.upsert({where:{slug:s},update:{name:n},create:{name:n,slug:s}})).id}
export async function PUT(request:NextRequest,{params}:RouteProps){const admin=await requireAdmin(request);if(!admin.ok)return admin.response;try{const{id}=await params;const body=await request.json();const previous=await prisma.startupTool.findUnique({where:{id}});if(!previous)return NextResponse.json({error:"Tool not found."},{status:404});const name=String(body.name??"").trim(),summary=String(body.summary??"").trim(),slug=slugify(String(body.slug??name)),thumbnail=String(body.thumbnail??"").trim(),price=priceValue(body.price);if(!name||!summary||!slug||!thumbnail||price===null)return NextResponse.json({error:"Name, summary, slug, thumbnail and valid price are required."},{status:400});const tool=await prisma.startupTool.update({where:{id},data:{name,slug,summary,description:String(body.description??summary).trim()||summary,price,thumbnail,screenshots:Array.isArray(body.screenshots)?body.screenshots.map(String).filter(Boolean):[],benefits:lines(body.benefits),includedFiles:lines(body.includedFiles),bestFor:lines(body.bestFor),instructions:String(body.instructions??"").trim()||null,faqs:body.faqs??null,categoryId:await categoryId(String(body.category??"SaaS"))}});revalidatePath("/");revalidatePath("/tools");revalidatePath(`/tools/${tool.slug}`);if(previous.slug!==tool.slug)revalidatePath(`/tools/${previous.slug}`);return NextResponse.json(tool)}catch(error){console.error(error);return NextResponse.json({error:"Unable to update tool."},{status:500})}}
export async function DELETE(request:NextRequest,{params}:RouteProps){const admin=await requireAdmin(request);if(!admin.ok)return admin.response;try{const{id}=await params;const tool=await prisma.startupTool.delete({where:{id}});revalidatePath("/");revalidatePath("/tools");revalidatePath(`/tools/${tool.slug}`);return NextResponse.json({ok:true})}catch(error){console.error(error);return NextResponse.json({error:"Unable to delete tool."},{status:500})}}
