import { NextRequest, NextResponse } from "next/server";
import { revalidatePath } from "next/cache";
import { requireAdmin } from "@/lib/admin-auth";
import { prisma } from "@/lib/prisma";

const MAX={name:120,role:120,company:120,avatarUrl:1000,content:2000};
function text(value:unknown,max:number){const v=String(value??"").trim();return v.length<=max?v:v.slice(0,max)}
function normalize(body:any){return{name:text(body?.name,MAX.name),role:text(body?.role,MAX.role),company:text(body?.company,MAX.company),avatarUrl:text(body?.avatarUrl,MAX.avatarUrl),content:text(body?.content,MAX.content),rating:Math.min(5,Math.max(1,Number.isFinite(Number(body?.rating))?Math.round(Number(body.rating)):5)),isPublished:Boolean(body?.isPublished)}}
export async function PUT(request:NextRequest,{params}:{params:Promise<{id:string}>}){const admin=await requireAdmin(request);if(!admin.ok)return admin.response;try{const {id}=await params;const data=normalize(await request.json());if(!data.name||data.content.length<3)return NextResponse.json({error:"Name and testimonial text are required."},{status:400});const rows=await prisma.$queryRaw<any[]>`UPDATE "Testimonial" SET "name"=${data.name},"role"=${data.role||null},"company"=${data.company||null},"avatarUrl"=${data.avatarUrl||null},"content"=${data.content},"rating"=${data.rating},"isPublished"=${data.isPublished},"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=${id} RETURNING *`;if(!rows.length)return NextResponse.json({error:"Testimonial not found."},{status:404});revalidatePath("/");return NextResponse.json(rows[0])}catch(error){console.error("Unable to update testimonial:",error);return NextResponse.json({error:"Unable to update testimonial."},{status:500})}}
export async function DELETE(request:NextRequest,{params}:{params:Promise<{id:string}>}){const admin=await requireAdmin(request);if(!admin.ok)return admin.response;try{const {id}=await params;const rows=await prisma.$queryRaw<any[]>`DELETE FROM "Testimonial" WHERE "id"=${id} RETURNING "id"`;if(!rows.length)return NextResponse.json({error:"Testimonial not found."},{status:404});revalidatePath("/");return NextResponse.json({ok:true,id})}catch(error){console.error("Unable to delete testimonial:",error);return NextResponse.json({error:"Unable to delete testimonial."},{status:500})}}
