"use client";

import { FormEvent, useEffect, useState } from "react";
import { Loader2, Pencil, Plus, Save, Star, Trash2, X } from "lucide-react";
import type { EditableTestimonial } from "@/lib/content-store";

const blank:EditableTestimonial={name:"",role:"",company:"",avatarUrl:"",content:"",rating:5,isPublished:true};
async function message(r:Response){try{const j=await r.json();if(j?.error)return String(j.error)}catch{}return `${r.status} ${r.statusText}`}
export default function TestimonialsAdmin(){
 const [items,setItems]=useState<EditableTestimonial[]>([]);const [form,setForm]=useState<EditableTestimonial>(blank);const [editing,setEditing]=useState<string|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [status,setStatus]=useState("");
 async function load(){setLoading(true);try{const r=await fetch('/api/admin/testimonials');if(!r.ok)throw new Error(await message(r));setItems(await r.json())}catch(e){setStatus(e instanceof Error?e.message:'Unable to load testimonials.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 function reset(){setEditing(null);setForm(blank)}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setStatus("");try{const url=editing?`/api/admin/testimonials/${editing}`:'/api/admin/testimonials';const r=await fetch(url,{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});if(!r.ok)throw new Error(await message(r));const saved=await r.json();setItems(c=>editing?c.map(x=>x.id===editing?{...x,...saved}:x):[saved,...c]);setStatus(editing?'Testimonial updated.':'Testimonial added.');reset()}catch(e){setStatus(e instanceof Error?e.message:'Unable to save testimonial.')}finally{setSaving(false)}}
 async function remove(id:string){if(!window.confirm('Delete this testimonial?'))return;setStatus("");const r=await fetch(`/api/admin/testimonials/${id}`,{method:'DELETE'});if(!r.ok){setStatus(await message(r));return}setItems(c=>c.filter(x=>x.id!==id));if(editing===id)reset();setStatus('Testimonial deleted.')}
 function edit(item:EditableTestimonial){setEditing(item.id??null);setForm({...item});window.scrollTo({top:0,behavior:'smooth'})}
 const input='mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none focus:border-indigo-500 dark:border-indigo-500/30 dark:bg-slate-950';const card='rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-indigo-500/20 dark:bg-slate-900/50';
 return <main className="min-h-screen bg-slate-50 px-4 py-10 text-slate-900 dark:bg-[#050505] dark:text-white"><div className="mx-auto max-w-7xl"><header className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><span className="inline-flex rounded-full border border-indigo-200 bg-indigo-50 px-3 py-1 text-xs font-bold uppercase tracking-[.18em] text-indigo-700 dark:border-indigo-500/30 dark:bg-indigo-950/30 dark:text-indigo-300">Admin · Testimonials</span><h1 className="mt-3 text-4xl font-extrabold tracking-tight">Client Testimonials</h1><p className="mt-2 text-slate-600 dark:text-slate-300">Add, edit, publish, or remove client feedback displayed on the homepage.</p></div><a href="/admin" className="rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold dark:border-indigo-500/30 dark:bg-slate-900">Back to Admin</a></header>{status&&<p className="mb-6 rounded-xl border border-indigo-200 bg-indigo-50 px-4 py-3 text-sm font-semibold text-indigo-700 dark:border-indigo-500/30 dark:bg-indigo-950/30 dark:text-indigo-200">{status}</p>}
 <section className={card}><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-bold">{editing?'Edit testimonial':'Add testimonial'}</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Only published testimonials appear publicly.</p></div>{editing&&<button type="button" onClick={reset} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 px-4 py-2 text-sm font-bold dark:border-slate-700"><X className="h-4 w-4"/>Cancel</button>}</div><form onSubmit={save} className="mt-6 grid gap-5 md:grid-cols-2"><label className="text-sm font-semibold">Name<input required className={input} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="text-sm font-semibold">Role<input className={input} value={form.role} onChange={e=>setForm({...form,role:e.target.value})}/></label><label className="text-sm font-semibold">Company<input className={input} value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/></label><label className="text-sm font-semibold">Avatar URL<input className={input} placeholder="https://..." value={form.avatarUrl} onChange={e=>setForm({...form,avatarUrl:e.target.value})}/></label><label className="text-sm font-semibold">Rating<select className={input} value={form.rating} onChange={e=>setForm({...form,rating:Number(e.target.value)})}>{[5,4,3,2,1].map(x=><option key={x} value={x}>{x} stars</option>)}</select></label><label className="flex items-center gap-3 pt-8 text-sm font-semibold"><input type="checkbox" checked={form.isPublished} onChange={e=>setForm({...form,isPublished:e.target.checked})} className="h-4 w-4"/>Published on homepage</label><label className="md:col-span-2 text-sm font-semibold">Testimonial<textarea required rows={6} className={input} value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/></label><button disabled={saving} className="md:col-span-2 inline-flex items-center justify-center gap-2 rounded-2xl bg-indigo-600 px-6 py-3.5 text-sm font-extrabold text-white hover:bg-indigo-500 disabled:opacity-60">{saving?<Loader2 className="h-5 w-5 animate-spin"/>:editing?<Save className="h-5 w-5"/>:<Plus className="h-5 w-5"/>}{editing?'Update testimonial':'Add testimonial'}</button></form></section>
 <section className="mt-8"><div className="mb-4 flex items-center gap-2"><h2 className="text-2xl font-bold">All testimonials</h2><span className="rounded-full bg-slate-200 px-2.5 py-1 text-xs font-bold dark:bg-slate-800">{items.length}</span></div>{loading?<div className="flex justify-center py-16"><Loader2 className="h-8 w-8 animate-spin text-indigo-500"/></div>:items.length===0?<div className={card+" text-center text-slate-500"}>No testimonials yet.</div>:<div className="grid gap-5 lg:grid-cols-2">{items.map(item=><article key={item.id} className={card}><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3">{item.avatarUrl?<img src={item.avatarUrl} alt={item.name} className="h-12 w-12 rounded-full object-cover"/>:<div className="flex h-12 w-12 items-center justify-center rounded-full bg-indigo-100 font-black text-indigo-700 dark:bg-indigo-950 dark:text-indigo-200">{item.name.slice(0,1).toUpperCase()}</div>}<div><h3 className="font-bold">{item.name}</h3><p className="text-sm text-slate-500">{[item.role,item.company].filter(Boolean).join(' · ')||'Client'}</p></div></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.isPublished?'bg-emerald-100 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300':'bg-slate-200 text-slate-600 dark:bg-slate-800 dark:text-slate-300'}`}>{item.isPublished?'Published':'Hidden'}</span></div><div className="mt-4 flex items-center gap-1">{Array.from({length:5},(_,i)=><Star key={i} className={`h-4 w-4 ${i<item.rating?'fill-current':'opacity-20'}`}/>)}</div><p className="mt-4 line-clamp-4 text-sm leading-6 text-slate-700 dark:text-slate-200">“{item.content}”</p><div className="mt-5 flex gap-2"><button onClick={()=>edit(item)} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 px-4 py-2 text-sm font-bold dark:border-slate-700"><Pencil className="h-4 w-4"/>Edit</button><button onClick={()=>item.id&&remove(item.id)} className="inline-flex items-center gap-2 rounded-xl border border-rose-200 px-4 py-2 text-sm font-bold text-rose-600 dark:border-rose-500/20"><Trash2 className="h-4 w-4"/>Delete</button></div></article>)}</div>}</section></div></main>
}
