"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Inbox, Loader2, MessageSquare } from "lucide-react";

type ContactMessage = { id: string; name: string; email: string; phone?: string; message: string; status: string; createdAt: string };

export default function AdminMessages() {
  const [messages, setMessages] = useState<ContactMessage[]>([]); const [isLoading, setIsLoading] = useState(true); const [error, setError] = useState("");
  async function loadMessages() { try { const response = await fetch("/api/admin/messages"); if (!response.ok) throw new Error("Failed to load messages"); setMessages(await response.json()); } catch { setError("Unable to load messages."); } finally { setIsLoading(false); } }
  useEffect(() => { void loadMessages(); }, []);
  async function setStatus(id: string, status: string) { const response = await fetch(`/api/admin/messages/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); if (!response.ok) { setError("Unable to update message status."); return; } const updated = await response.json(); setMessages(current => current.map(item => item.id === id ? { ...item, status: updated.status } : item)); }
  return <main className="flex-1 bg-slate-50 px-4 py-10 text-slate-900 dark:bg-[#050505] dark:text-white min-h-[90vh]"><div className="mx-auto max-w-5xl"><header className="mb-8 rounded-2xl border border-slate-200 bg-white p-6 dark:border-indigo-500/20 dark:bg-slate-900/40"><div className="flex items-center gap-4 mb-4"><Link href="/admin" className="p-2 rounded-full hover:bg-slate-100 dark:hover:bg-slate-800"><ArrowLeft className="h-5 w-5"/></Link><span className="inline-flex items-center gap-2 rounded-full border border-indigo-200 bg-indigo-50 px-3 py-1 text-sm font-semibold text-indigo-700 dark:border-indigo-500/30 dark:bg-indigo-950/30 dark:text-indigo-200"><Inbox className="h-4 w-4"/>Inbox</span></div><h1 className="text-3xl font-extrabold">User Messages</h1><p className="mt-2 text-slate-600 dark:text-slate-300">Messages submitted through the Contact page are stored in Supabase.</p></header>{isLoading?<div className="flex justify-center p-12"><Loader2 className="h-8 w-8 animate-spin text-indigo-500"/></div>:error?<p className="rounded-xl border border-red-200 bg-red-50 p-6 text-red-700">{error}</p>:messages.length===0?<div className="rounded-2xl border border-dashed p-12 text-center"><MessageSquare className="mx-auto mb-4 h-12 w-12 text-slate-300"/><h3 className="text-xl font-bold">No messages yet</h3></div>:<div className="grid gap-4">{messages.map(msg=><article key={msg.id} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-indigo-500/20 dark:bg-slate-900/40"><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div className="flex-1"><h3 className="text-lg font-bold">{msg.name} <span className="ml-2 text-sm font-normal text-slate-500">&lt;{msg.email}&gt;</span></h3><div className="mb-4 mt-1 text-xs uppercase tracking-widest text-slate-400">{new Date(msg.createdAt).toLocaleString()} · {msg.status}</div><p className="whitespace-pre-wrap rounded-xl border bg-slate-50 p-4 text-slate-700 dark:border-slate-800 dark:bg-slate-950 dark:text-slate-300">{msg.message}</p></div><div className="flex gap-2"><button onClick={()=>void setStatus(msg.id,"READ")} className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold text-white">Read</button><button onClick={()=>void setStatus(msg.id,"UNREAD")} className="rounded-lg border px-3 py-2 text-xs font-bold">Unread</button><button onClick={()=>void setStatus(msg.id,"ARCHIVED")} className="rounded-lg bg-slate-800 px-3 py-2 text-xs font-bold text-white">Archive</button></div></div></article>)}</div>}</div></main>;
}
