"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
type Entity={id:string;name?:string;title?:string;slug:string};type Row={id:string;title:string;description:string;ogImage?:string|null;slug?:string|null;service?:Entity|null;startupTool?:Entity|null;blogPost?:Entity|null;portfolioProject?:Entity|null};
export default function AdminSeo(){const[rows,setRows]=useState<Row[]>([]);const[status,setStatus]=useState("");const[form,setForm]=useState({kind:"service",entityId:"",title:"",description:"",ogImage:"",slug:""});const[entities,setEntities]=useState<Entity[]>([]);
async function load(){try{const r=await fetch('/api/admin/seo');if(!r.ok)throw 0;const data=await r.json();setRows(data);const key=form.kind==='service'?'service':form.kind==='tool'?'startupTool':form.kind==='blog'?'blogPost':'portfolioProject';setEntities(data.map((x:Row)=>x[key]).filter(Boolean).map((x:Entity)=>({id:x.id,name:x.name??x.title,slug:x.slug})))}catch{setStatus('Unable to load SEO data.')}}useEffect(()=>{void load()},[]);
async function save(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/admin/seo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(!r.ok){setStatus(j.error??'Unable to save SEO.');return}setStatus('SEO metadata saved.');await load()}
function selectKind(kind:string){setForm(f=>({...f,kind,entityId:""}));}
return <main className="min-h-screen bg-slate-50 px-4 py-10 dark:bg-[#050505] dark:text-white"><div className="mx-auto max-w-6xl"><div className="mb-8 flex items-end justify-between"><div><h1 className="text-4xl font-extrabold">SEO Metadata</h1><p className="mt-2 text-slate-500 dark:text-slate-300">Manage SeoMetadata rows linked to services, tools, blog posts and portfolio projects.</p></div><Link href="/admin" className="rounded-lg border px-4 py-2 font-bold">Back</Link></div>{status&&<p className="mb-6 rounded-xl border bg-indigo-50 px-4 py-3 text-sm font-semibold text-indigo-700">{status}</p>}<form onSubmit={save} className="rounded-3xl border bg-white p-6 dark:border-indigo-500/20 dark:bg-slate-900/50"><div className="grid gap-4 md:grid-cols-2"><select value={form.kind} onChange={e=>selectKind(e.target.value)} className="rounded-xl border p-3 dark:bg-slate-950"><option value="service">Service</option><option value="tool">Startup Tool</option><option value="blog">Blog Post</option><option value="portfolio">Portfolio Project</option></select><select value={form.entityId} onChange={e=>setForm({...form,entityId:e.target.value})} className="rounded-xl border p-3 dark:bg-slate-950" required><option value="">Select entity</option>{entities.map(e=><option key={e.id} value={e.id}>{e.name} · {e.slug}</option>)}</select><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="SEO title" className="rounded-xl border p-3 dark:bg-slate-950" required/><input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} placeholder="SEO slug" className="rounded-xl border p-3 dark:bg-slate-950"/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="SEO description" rows={5} className="md:col-span-2 rounded-xl border p-3 dark:bg-slate-950" required/><input value={form.ogImage} onChange={e=>setForm({...form,ogImage:e.target.value})} placeholder="OG image URL" className="md:col-span-2 rounded-xl border p-3 dark:bg-slate-950"/></div><button className="mt-5 rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white">Save SEO</button></form><section className="mt-8 rounded-3xl border bg-white p-6 dark:border-indigo-500/20 dark:bg-slate-900/50"><h2 className="text-xl font-bold">Current SEO Records ({rows.length})</h2><div className="mt-4 space-y-3">{rows.map(r=><article key={r.id} className="rounded-xl border p-4 dark:border-slate-800"><p className="font-bold">{r.title}</p><p className="mt-1 text-sm text-slate-500">{r.description}</p></article>)}</div></section></div></main>}
