import Image from "next/image";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { prisma } from "@/lib/prisma";

export default async function FeaturedPortfolio({ title, description }: { title:string; description:string }) {
  const projects = await prisma.portfolioProject.findMany({ orderBy:{ createdAt:"desc" }, take:3 });
  return <section className="py-24 relative z-10"><div className="container mx-auto px-4"><div className="mb-12 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="max-w-2xl"><h2 className="text-3xl font-bold tracking-tight text-slate-900 dark:text-white sm:text-4xl">{title}</h2><p className="mt-4 text-lg text-slate-600 dark:text-slate-300">{description}</p></div><Link href="/portfolio" className="inline-flex items-center gap-1 font-semibold text-indigo-600 dark:text-indigo-400">View portfolio <ArrowRight className="h-4 w-4"/></Link></div>{projects.length===0?<div className="rounded-2xl border border-dashed border-slate-300 p-10 text-center text-slate-500 dark:border-indigo-500/20">No featured projects yet.</div>:<div className="grid gap-8 md:grid-cols-3">{projects.map((project)=><Link key={project.id} href={`/portfolio/${project.slug}`} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-md transition hover:-translate-y-1 hover:border-indigo-400/60 hover:shadow-xl dark:border-indigo-500/20 dark:bg-slate-900/40"><div className={`relative h-56 overflow-hidden bg-gradient-to-br ${project.gradient}`}>{project.gallery[0]?<Image src={project.gallery[0]} alt={project.title} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition duration-500 group-hover:scale-105"/>:null}</div><div className="p-6"><p className="text-xs font-bold uppercase tracking-wider text-indigo-600 dark:text-indigo-300">{project.tags[0]??'Selected Work'}</p><h3 className="mt-2 text-xl font-extrabold text-slate-950 dark:text-white">{project.title}</h3><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{project.summary}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-indigo-700 dark:text-indigo-300">View project <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></span></div></Link>)}</div>}</div></section>;
}
