import Link from "next/link";
import { Check, Crown, Sparkles } from "lucide-react";
import { getPricingPlans } from "@/lib/content-store";

function formatPrice(price:number,currency:string){return price===0?"Free":`${price.toFixed(price%1?3:0).replace(/0+$/,'').replace(/\.$/,'')} ${currency}`}

export default async function PricingPlans({limit}:{limit?:number}={}){
  const plans=(await getPricingPlans({publishedOnly:true})).slice(0,limit??12);
  if(!plans.length)return null;
  return <section className="px-4 py-24"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-3xl text-center"><span className="inline-flex items-center gap-2 rounded-full border border-indigo-200 bg-indigo-50 px-3 py-1 text-xs font-bold uppercase tracking-[.18em] text-indigo-700 dark:border-indigo-500/30 dark:bg-indigo-950/30 dark:text-indigo-300"><Sparkles className="h-3.5 w-3.5"/>Pricing</span><h2 className="mt-4 text-4xl font-extrabold tracking-tight text-slate-950 dark:text-white">Plans built around your next move</h2><p className="mt-4 text-lg leading-8 text-slate-600 dark:text-slate-300">Clear options for brands, startups, and businesses ready to build, improve, or launch.</p></div><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{plans.map(plan=><article key={plan.id} className={`relative flex h-full flex-col rounded-[28px] border bg-white p-7 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-2xl dark:bg-slate-900/60 ${plan.isPopular?'border-indigo-500 ring-2 ring-indigo-500/15 dark:border-indigo-400':'border-slate-200 dark:border-indigo-500/20'}`}>{plan.isPopular?<div className="absolute -top-3 left-1/2 flex -translate-x-1/2 items-center gap-1 rounded-full bg-indigo-600 px-3 py-1 text-[11px] font-black uppercase tracking-[.16em] text-white"><Crown className="h-3.5 w-3.5"/>Most popular</div>:null}<h3 className="text-2xl font-extrabold text-slate-950 dark:text-white">{plan.name}</h3><p className="mt-3 min-h-14 text-sm leading-6 text-slate-600 dark:text-slate-300">{plan.description}</p><div className="mt-7"><span className="text-4xl font-black tracking-tight text-slate-950 dark:text-white">{formatPrice(plan.price,plan.currency)}</span>{plan.price>0?<span className="ml-2 text-sm font-semibold text-slate-400">project starting</span>:null}</div><div className="mt-7 flex-1 space-y-3">{plan.features.map(feature=><div key={feature} className="flex gap-3 text-sm leading-6 text-slate-700 dark:text-slate-200"><Check className="mt-1 h-4 w-4 shrink-0 text-indigo-600 dark:text-indigo-300"/><span>{feature}</span></div>)}</div><Link href={plan.ctaHref} className={`mt-8 inline-flex items-center justify-center rounded-xl px-5 py-3.5 text-sm font-bold transition ${plan.isPopular?'bg-indigo-600 text-white hover:bg-indigo-500':'border border-slate-200 bg-slate-50 text-slate-900 hover:border-indigo-300 hover:bg-indigo-50 dark:border-slate-800 dark:bg-slate-950 dark:text-white dark:hover:bg-indigo-950/40'}`}>{plan.ctaLabel}</Link></article>)}</div></div></section>;
}
