import { getTestimonials } from "@/lib/content-store";
import { Quote, Star } from "lucide-react";

export default async function Testimonials(){
  let testimonials=[];
  try{testimonials=await getTestimonials({publishedOnly:true,limit:6})}catch(error){console.error("Unable to load testimonials:",error)}
  if(!testimonials.length)return null;
  return <section className="px-4 py-24"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-3xl text-center"><span className="inline-flex rounded-full border border-indigo-200 bg-indigo-50 px-3 py-1 text-xs font-bold uppercase tracking-[.18em] text-indigo-700 dark:border-indigo-500/30 dark:bg-indigo-950/30 dark:text-indigo-300">Client feedback</span><h2 className="mt-4 text-4xl font-extrabold tracking-tight text-slate-950 dark:text-white">What our clients say</h2><p className="mt-4 text-lg leading-8 text-slate-600 dark:text-slate-300">Real feedback from people who trusted SpaceZone with their next digital move.</p></div><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{testimonials.map((item)=><article key={item.id} className="group relative overflow-hidden rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl dark:border-indigo-500/20 dark:bg-slate-900/60"><div className="absolute right-5 top-5 opacity-10 transition group-hover:opacity-20"><Quote className="h-14 w-14"/></div><div className="flex items-center gap-1">{Array.from({length:5},(_,i)=><Star key={i} className={`h-4 w-4 ${i<item.rating?'fill-current':'opacity-20'}`}/>)}</div><p className="relative mt-5 text-base leading-7 text-slate-700 dark:text-slate-200">“{item.content}”</p><div className="mt-7 flex items-center gap-3">{item.avatarUrl?<img src={item.avatarUrl} alt={item.name} className="h-11 w-11 rounded-full object-cover"/>:<div className="flex h-11 w-11 items-center justify-center rounded-full bg-indigo-100 text-sm font-black text-indigo-700 dark:bg-indigo-950 dark:text-indigo-200">{item.name.slice(0,1).toUpperCase()}</div>}<div className="min-w-0"><div className="truncate font-bold text-slate-950 dark:text-white">{item.name}</div><div className="truncate text-sm text-slate-500 dark:text-slate-400">{[item.role,item.company].filter(Boolean).join(" · ")||"Client"}</div></div></div></article>)}</div></div></section>;
}
