import { prisma } from "@/lib/prisma";

export type EditableService = { id?:string; slug:string; name:string; summary:string; description:string; icon:"code"|"rocket"|"sparkles"|"image"; image?:string|null; deliverables:string[]; process:string[]; bestFor:string[] };
export type EditableStartupTool = { id?:string; slug:string; name:string; summary:string; description:string; price:number; priceLabel:string; category:string; thumbnail:string|null; screenshots:string[]; benefits:string[]; includedFiles:string[]; bestFor:string[]; instructions:string|null; faqs:unknown };
export function slugify(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")}
function linesToList(value:string|null|undefined){return(value??"").split("\n").map(x=>x.trim()).filter(Boolean)}
function iconForService(slug:string,name:string):EditableService["icon"]{const key=`${slug} ${name}`.toLowerCase();if(key.includes("web")||key.includes("app"))return"code";if(key.includes("seo")||key.includes("marketing"))return"rocket";if(key.includes("banner")||key.includes("store"))return"image";return"sparkles"}
function formatPrice(price:number){return Number.isInteger(price)?`$${price}`:`$${price.toFixed(3).replace(/0+$/,'').replace(/\.$/,'')}`}
function mapServiceRecord(record:any):EditableService{return{id:record.id,slug:record.slug,name:record.name,summary:record.summary,description:record.description,icon:iconForService(record.slug,record.name),image:record.imageUrl??null,deliverables:linesToList(record.examples),process:linesToList(record.workflow),bestFor:linesToList(record.bestFor)}}
function mapToolRecord(record:any):EditableStartupTool{const price=Number(record.price);return{id:record.id,slug:record.slug,name:record.name,summary:record.summary,description:record.description,price,priceLabel:formatPrice(price),category:record.category.name,thumbnail:record.thumbnail,screenshots:record.screenshots??[],benefits:record.benefits??[],includedFiles:record.includedFiles??[],bestFor:record.bestFor??[],instructions:record.instructions??null,faqs:record.faqs??null}}
export async function getEditableServices(){const records=await prisma.service.findMany({orderBy:{createdAt:"asc"}});if(!records.length)return[];const media=await prisma.serviceMedia.findMany({where:{serviceId:{in:records.map(r=>r.id)}},select:{serviceId:true,imageUrl:true}});const map=new Map(media.map(r=>[r.serviceId,r.imageUrl]));return records.map(r=>mapServiceRecord({...r,imageUrl:map.get(r.id)??null}))}
export async function getEditableService(slug:string){const record=await prisma.service.findUnique({where:{slug}});if(!record)return undefined;const media=await prisma.serviceMedia.findUnique({where:{serviceId:record.id},select:{imageUrl:true}});return mapServiceRecord({...record,imageUrl:media?.imageUrl??null})}
export async function getEditableStartupTools(){const records=await prisma.startupTool.findMany({include:{category:true},orderBy:{createdAt:"asc"}});return records.map(mapToolRecord)}
export async function getEditableStartupTool(slug:string){const record=await prisma.startupTool.findUnique({where:{slug},include:{category:true}});return record?mapToolRecord(record):undefined}
