import { NextRequest, NextResponse } from "next/server";
import { revalidatePath } from "next/cache";
import { requireAdmin } from "@/lib/admin-auth";
import { prisma } from "@/lib/prisma";

const MAX={name:120,slug:120,description:1000,currency:10,ctaLabel:100,ctaHref:500,feature:200};
function bounded(value:unknown,max:number){return String(value??"").trim().slice(0,max)}
function list(value:unknown){return Array.isArray(value)?value.map(v=>bounded(v,MAX.feature)).filter(Boolean).slice(0,20):[]}
function slugify(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")}
function payload(body:any){const name=bounded(body?.name,MAX.name);const slug=slugify(bounded(body?.slug||name,MAX.slug));const price=Number(body?.price);return{name,slug,description:bounded(body?.description,MAX.description),price:Number.isFinite(price)?Math.max(0,Math.min(999999,price)):0,currency:bounded(body?.currency||"BHD",MAX.currency).toUpperCase(),features:list(body?.features),ctaLabel:bounded(body?.ctaLabel||"Get started",MAX.ctaLabel),ctaHref:bounded(body?.ctaHref||"/contact",MAX.ctaHref),isPopular:Boolean(body?.isPopular),isPublished:Boolean(body?.isPublished),sortOrder:Number.isFinite(Number(body?.sortOrder))?Math.max(0,Math.min(9999,Math.round(Number(body.sortOrder)))):0}}
export async function PUT(request:NextRequest,{params}:{params:Promise<{id:string}>}){const admin=await requireAdmin(request);if(!admin.ok)return admin.response;try{const {id}=await params;const data=payload(await request.json());if(!data.name||!data.slug||!data.description)return NextResponse.json({error:"Name, slug, and description are required."},{status:400});const conflict=await prisma.$queryRaw<any[]>`SELECT "id" FROM "PricingPlan" WHERE "slug"=${data.slug} AND "id"<>${id} LIMIT 1`;if(conflict.length)return NextResponse.json({error:"A pricing plan with this slug already exists."},{status:409});const rows=await prisma.$queryRaw<any[]>`UPDATE "PricingPlan" SET "name"=${data.name},"slug"=${data.slug},"description"=${data.description},"price"=${data.price},"currency"=${data.currency},"features"=${JSON.stringify(data.features)}::jsonb,"ctaLabel"=${data.ctaLabel},"ctaHref"=${data.ctaHref},"isPopular"=${data.isPopular},"isPublished"=${data.isPublished},"sortOrder"=${data.sortOrder},"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=${id} RETURNING *`;if(!rows.length)return NextResponse.json({error:"Pricing plan not found."},{status:404});revalidatePath("/pricing");revalidatePath("/");return NextResponse.json(rows[0])}catch(error){console.error("Unable to update pricing plan:",error);return NextResponse.json({error:"Unable to update pricing plan."},{status:500})}}
export async function DELETE(request:NextRequest,{params}:{params:Promise<{id:string}>}){const admin=await requireAdmin(request);if(!admin.ok)return admin.response;try{const {id}=await params;const rows=await prisma.$queryRaw<any[]>`DELETE FROM "PricingPlan" WHERE "id"=${id} RETURNING "id"`;if(!rows.length)return NextResponse.json({error:"Pricing plan not found."},{status:404});revalidatePath("/pricing");revalidatePath("/");return NextResponse.json({ok:true})}catch(error){console.error("Unable to delete pricing plan:",error);return NextResponse.json({error:"Unable to delete pricing plan."},{status:500})}}
