"use client";
import { FormEvent, useEffect, useState } from "react";
import { Loader2, Plus, Save, Trash2, X } from "lucide-react";

type Faq={id?:string;question:string;answer:string;category:string;page:string;sortOrder:number;isPublished:boolean};
const empty:Faq={question:"",answer:"",category:"",page:"/",sortOrder:0,isPublished:true};
const headers={"Content-Type":"application/json"};
async function message(r:Response){try{const j=await r.json();if(j?.error)return String(j.error)}catch{}return `${r.status} ${r.statusText}`}
export default function AdminFaq(){const [items,setItems]=useState<Faq[]>([]);const [form,setForm]=useState<Faq>(empty);const [loading,setLoading]=useState(false);const [status,setStatus]=useState("");
async function load(){setLoading(true);try{const r=await fetch('/api/admin/faq',{headers});if(!r.ok)throw new Error(await message(r));setItems(await r.json())}catch(e){setStatus(e instanceof Error?e.message:'Unable to load FAQs.')}finally{setLoading(false)}}
useEffect(()=>{void load()},[]);
async function save(e:FormEvent){e.preventDefault();if(!form.question.trim()||!form.answer.trim()){setStatus('Question and answer are required.');return}setLoading(true);try{const r=await fetch(form.id?`/api/admin/faq/${form.id}`:'/api/admin/faq',{method:form.id?'PUT':'POST',headers,body:JSON.stringify({...form,sortOrder:Number(form.sortOrder)||0})});if(!r.ok)throw new Error(await message(r));setStatus(form.id?'FAQ updated.':'FAQ created.');setForm(empty);await load()}catch(e){setStatus(e instanceof Error?e.message:'Unable to save FAQ.')}finally{setLoading(false)}}
async function remove(id?:string){if(!id||!confirm('Delete this FAQ?'))return;setLoading(true);try{const r=await fetch(`/api/admin/faq/${id}`,{method:'DELETE'});if(!r.ok)throw new Error(await message(r));setStatus('FAQ deleted.');if(form.id===id)setForm(empty);await load()}catch(e){setStatus(e instanceof Error?e.message:'Unable to delete FAQ.')}finally{setLoading(false)}}
return <main className="min-h-screen bg-slate-50 px-4 py-10 text-slate-900 dark:bg-[#050505] dark:text-white"><div className="mx-auto max-w-7xl"><header className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><span className="inline-flex rounded-full border border-indigo-200 bg-indigo-50 px-3 py-1 text-xs font-bold uppercase tracking-[.18em] text-indigo-700 dark:border-indigo-500/30 dark:bg-indigo-950/30 dark:text-indigo-300">Admin · FAQ</span><h1 className="mt-3 text-4xl font-extrabold">Frequently Asked Questions</h1><p className="mt-2 max-w-2xl text-slate-600 dark:text-slate-300">Manage questions, answers, page placement, visibility, and display order.</p></div><a href="/admin" className="rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold dark:border-indigo-500/30 dark:bg-slate-900">Back to Admin</a></header>{status?<p className="mb-6 rounded-xl border border-indigo-200 bg-indigo-50 px-4 py-3 text-sm font-semibold text-indigo-700 dark:border-indigo-500/30 dark:bg-indigo-950/30 dark:text-indigo-200">{status}</p>:null}
<div className="grid gap-8 lg:grid-cols-[.85fr_1.15fr]"><form onSubmit={save} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-indigo-500/20 dark:bg-slate-900/50"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">{form.id?'Edit FAQ':'Add FAQ'}</h2>{form.id?<button type="button" onClick={()=>setForm(empty)} className="inline-flex items-center gap-1 text-sm font-semibold text-slate-500"><X className="h-4 w-4"/>Cancel</button>:null}</div><label className="mt-5 block text-sm font-semibold">Question<textarea required rows={3} value={form.question} onChange={e=>setForm({...form,question:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-300 bg-white p-3 dark:border-indigo-500/30 dark:bg-slate-950"/></label><label className="mt-4 block text-sm font-semibold">Answer<textarea required rows={8} value={form.answer} onChange={e=>setForm({...form,answer:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-300 bg-white p-3 dark:border-indigo-500/30 dark:bg-slate-950"/></label><label className="mt-4 block text-sm font-semibold">Category<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-300 bg-white p-3 dark:border-indigo-500/30 dark:bg-slate-950"/></label><label className="mt-4 block text-sm font-semibold">Page path<input value={form.page} onChange={e=>setForm({...form,page:e.target.value||'/'})} placeholder="/" className="mt-2 w-full rounded-xl border border-slate-300 bg-white p-3 dark:border-indigo-500/30 dark:bg-slate-950"/></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold">Sort order<input type="number" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:Number(e.target.value)})} className="mt-2 w-full rounded-xl border border-slate-300 bg-white p-3 dark:border-indigo-500/30 dark:bg-slate-950"/></label><label className="flex items-center gap-3 self-end rounded-xl border border-slate-200 p-3 text-sm font-semibold dark:border-slate-800"><input type="checkbox" checked={form.isPublished} onChange={e=>setForm({...form,isPublished:e.target.checked})} className="h-4 w-4"/>Published</label></div><button disabled={loading} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white disabled:opacity-60">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}{form.id?'Save Changes':'Create FAQ'}</button></form>
<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-indigo-500/20 dark:bg-slate-900/50"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Current FAQs</h2><span className="text-sm text-slate-500">{items.length} items</span></div><div className="mt-5 space-y-3">{items.map(item=><article key={item.id} className="rounded-2xl border border-slate-200 p-5 dark:border-slate-800"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider ${item.isPublished?'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{item.isPublished?'Published':'Hidden'}</span>{item.category?<span className="text-xs font-semibold text-indigo-600 dark:text-indigo-300">{item.category}</span>:null}<span className="text-xs text-slate-400">{item.page}</span></div><h3 className="mt-3 font-bold">{item.question}</h3><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-6 text-slate-600 dark:text-slate-300">{item.answer}</p></div><div className="flex shrink-0 gap-2"><button onClick={()=>setForm(item)} className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold text-white"><Plus className="mr-1 inline h-3.5 w-3.5 rotate-45"/>Edit</button><button onClick={()=>void remove(item.id)} className="rounded-lg bg-red-600 px-3 py-2 text-white"><Trash2 className="h-4 w-4"/></button></div></div></article>)}</div></section></div></div></main>}
