"use client";

import { FormEvent, useEffect, useState } from "react";
import { Loader2, Save, X } from "lucide-react";
import type { EditableHomePage } from "@/lib/content-store";

const emptyWhy = { title:"", text:"" };
function headers(){return {"Content-Type":"application/json"};}
async function errorMessage(response:Response){try{const json=await response.json();if(json?.error)return String(json.error)}catch{}return `${response.status} ${response.statusText}`}

export default function AdminHomePage(){
 const [form,setForm]=useState<EditableHomePage|null>(null); const [status,setStatus]=useState(""); const [loading,setLoading]=useState(false);
 async function load(){setLoading(true);setStatus("");try{const r=await fetch('/api/admin/home',{headers:headers()});if(!r.ok)throw new Error(await errorMessage(r));setForm(await r.json())}catch(e){setStatus(e instanceof Error?e.message:'Unable to load homepage.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 function update<K extends keyof EditableHomePage>(key:K,value:EditableHomePage[K]){setForm(c=>c?{...c,[key]:value}:c)}
 function updateWhy(index:number,key:'title'|'text',value:string){if(!form)return;const items=form.whyItems.map((item,i)=>i===index?{...item,[key]:value}:item);update('whyItems',items)}
 async function save(e:FormEvent){e.preventDefault();if(!form)return;setLoading(true);setStatus("");try{const r=await fetch('/api/admin/home',{method:'PUT',headers:headers(),body:JSON.stringify(form)});if(!r.ok)throw new Error(await errorMessage(r));setForm(await r.json());setStatus('Homepage updated successfully.')}catch(e){setStatus(e instanceof Error?e.message:'Unable to save homepage.')}finally{setLoading(false)}}
 if(!form)return <main className="flex min-h-screen items-center justify-center bg-slate-50 dark:bg-[#050505]"><Loader2 className="h-8 w-8 animate-spin text-indigo-500"/></main>;
 const input='mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none focus:border-indigo-500 dark:border-indigo-500/30 dark:bg-slate-950';
 const card='rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-indigo-500/20 dark:bg-slate-900/50';
 return <main className="min-h-screen bg-slate-50 px-4 py-10 text-slate-900 dark:bg-[#050505] dark:text-white"><div className="mx-auto max-w-7xl"><header className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><span className="inline-flex rounded-full border border-indigo-200 bg-indigo-50 px-3 py-1 text-xs font-bold uppercase tracking-[.18em] text-indigo-700 dark:border-indigo-500/30 dark:bg-indigo-950/30 dark:text-indigo-300">Admin · Homepage</span><h1 className="mt-3 text-4xl font-extrabold tracking-tight">Edit Homepage</h1><p className="mt-2 text-slate-600 dark:text-slate-300">Control the homepage messaging, section copy, feature order, and final call to action.</p></div><a href="/admin" className="rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold dark:border-indigo-500/30 dark:bg-slate-900">Back to Admin</a></header>{status&&<p className="mb-6 rounded-xl border border-indigo-200 bg-indigo-50 px-4 py-3 text-sm font-semibold text-indigo-700 dark:border-indigo-500/30 dark:bg-indigo-950/30 dark:text-indigo-200">{status}</p>}
 <form onSubmit={save} className="space-y-8">
  <section className={card}><h2 className="text-xl font-bold">Hero</h2><div className="mt-5 grid gap-5 lg:grid-cols-2"><label className="block text-sm font-semibold">Badge<input className={input} value={form.badge} onChange={e=>update('badge',e.target.value)}/></label><label className="block text-sm font-semibold lg:col-span-2">Headline<textarea className={input} rows={3} value={form.heroTitle} onChange={e=>update('heroTitle',e.target.value)}/></label><label className="block text-sm font-semibold">Highlight text<input className={input} value={form.heroHighlight} onChange={e=>update('heroHighlight',e.target.value)}/></label><label className="block text-sm font-semibold lg:col-span-2">Description<textarea className={input} rows={4} value={form.heroDescription} onChange={e=>update('heroDescription',e.target.value)}/></label></div></section>
  <section className={card}><h2 className="text-xl font-bold">Hero actions</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><label className="block text-sm font-semibold">Primary label<input className={input} value={form.primaryCtaLabel} onChange={e=>update('primaryCtaLabel',e.target.value)}/></label><label className="block text-sm font-semibold">Primary link<input className={input} value={form.primaryCtaHref} onChange={e=>update('primaryCtaHref',e.target.value)}/></label><label className="block text-sm font-semibold">Secondary label<input className={input} value={form.secondaryCtaLabel} onChange={e=>update('secondaryCtaLabel',e.target.value)}/></label><label className="block text-sm font-semibold">Secondary link<input className={input} value={form.secondaryCtaHref} onChange={e=>update('secondaryCtaHref',e.target.value)}/></label></div></section>
  <section className={card}><h2 className="text-xl font-bold">Homepage sections</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><label className="block text-sm font-semibold">Services title<input className={input} value={form.servicesTitle} onChange={e=>update('servicesTitle',e.target.value)}/></label><label className="block text-sm font-semibold">Services description<textarea className={input} rows={3} value={form.servicesDescription} onChange={e=>update('servicesDescription',e.target.value)}/></label><label className="block text-sm font-semibold">Tools title<input className={input} value={form.toolsTitle} onChange={e=>update('toolsTitle',e.target.value)}/></label><label className="block text-sm font-semibold">Tools description<textarea className={input} rows={3} value={form.toolsDescription} onChange={e=>update('toolsDescription',e.target.value)}/></label><label className="block text-sm font-semibold">Portfolio title<input className={input} value={form.portfolioTitle} onChange={e=>update('portfolioTitle',e.target.value)}/></label><label className="block text-sm font-semibold">Portfolio description<textarea className={input} rows={3} value={form.portfolioDescription} onChange={e=>update('portfolioDescription',e.target.value)}/></label><label className="block text-sm font-semibold">Why title<input className={input} value={form.whyTitle} onChange={e=>update('whyTitle',e.target.value)}/></label><label className="block text-sm font-semibold">Why description<textarea className={input} rows={3} value={form.whyDescription} onChange={e=>update('whyDescription',e.target.value)}/></label></div></section>
  <section className={card}><h2 className="text-xl font-bold">Why SpaceZone cards</h2><div className="mt-5 grid gap-4 lg:grid-cols-3">{form.whyItems.map((item,i)=><div key={i} className="rounded-2xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-950/60"><label className="block text-sm font-semibold">Title<input className={input} value={item.title||emptyWhy.title} onChange={e=>updateWhy(i,'title',e.target.value)}/></label><label className="mt-4 block text-sm font-semibold">Text<textarea className={input} rows={6} value={item.text||emptyWhy.text} onChange={e=>updateWhy(i,'text',e.target.value)}/></label></div>)}</div></section>
  <section className={card}><h2 className="text-xl font-bold">Final CTA</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><label className="block text-sm font-semibold">Title<input className={input} value={form.finalCtaTitle} onChange={e=>update('finalCtaTitle',e.target.value)}/></label><label className="block text-sm font-semibold">Button label<input className={input} value={form.finalCtaLabel} onChange={e=>update('finalCtaLabel',e.target.value)}/></label><label className="block text-sm font-semibold md:col-span-2">Description<textarea className={input} rows={4} value={form.finalCtaDescription} onChange={e=>update('finalCtaDescription',e.target.value)}/></label><label className="block text-sm font-semibold">Button link<input className={input} value={form.finalCtaHref} onChange={e=>update('finalCtaHref',e.target.value)}/></label></div></section>
  <button disabled={loading} className="sticky bottom-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-indigo-600 px-6 py-4 text-sm font-extrabold text-white shadow-xl hover:bg-indigo-500 disabled:opacity-60">{loading?<Loader2 className="h-5 w-5 animate-spin"/>:<Save className="h-5 w-5"/>}{loading?'Saving...':'Save Homepage'}</button>
 </form></div></main>
}
